export const FromCurrencyCodes = {
  // BTC: 'Bitcoin',
  // ETH: 'Ethereum',
  // XRP: 'XRP',
  // LTC: 'Litecoin',
  // ETC: 'Ethereum Classic',
  // DASH: 'Dash',
  // MIOTA: 'IOTA',
  // XMR: 'Monero',
  // ADA: 'Cardano',
  BTC: 'BTC',
  ETH: 'ETH',
  XRP: 'XRP',
  LTC: 'LTC',
  ETC: 'ETC',
  DASH: 'DASH',
  MIOTA: 'MIOTA',
  XMR: 'XMR',
  ADA: 'ADA',
};
